filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/robo-shop/{{APP_NAME}}.log
  multiline.pattern: "^[A-Z][a-z][a-z] [0-9][0-9], [0-9][0-9][0-9][0-9]"
  multiline.negate: true
  multiline.match: after
  fields:
    APP_NAME: {{APP_NAME}} 

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1

output.logstash:
  hosts: ["{{LOGSTASH_ENDPOINT}}:5044"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
