- name: Demo on find and remove 
  hosts: all 
  tasks:
    - name: Find files 
      find:
        paths: /tmp/demo
        file_type: any 
      register: out 

    - name: List files 
      debug:
        msg: "{{out}}"

    - name: Delete files 
      file:
        path: "{{item.path}}"
        state: absent 
      loop: "{{out.files}}"