- name: Wait_for example 
  hosts: all 
  tasks:
    - name: Helloo 
      debug:
        msg: Heloo 

    - name: Wait for 
      wait_for:
        port: 22
        host: nginx-robo-shop-dev.devopsb45.internal
      connection: local