- name: Install Redis repo 
  package:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present 

- name: Install Redis 
  yum:
    name: redis
    state: present 
    enablerepo: remi

- name: Change redis port 
  lineinfile:
    path: /etc/redis.conf
    regexp: '^bind'
    line: bind 0.0.0.0

- name: Start Redis 
  service:
    name: redis 
    state: started 
    enabled: yes 
