- name: CLone the repo 
  import_role:
    name: app-clone
  vars:
    ACTION: clone 

- name: Import App Setup Role
  import_role:
    name: nodejs
    tasks_from: app-setup
  vars:
    APP_NAME: cart

- name: Update Catalogue URL 
  replace:
    path: /etc/systemd/system/cart.service
    regexp: 'CATALOGUEHOST'
    replace: "{{CATALOGUE_NAME}}" 

- name: Update Redis URL 
  replace:
    path: /etc/systemd/system/cart.service
    regexp: 'REDISHOST'
    replace: "{{REDIS_NAME}}" 

- name: SystemD Dameon-Reload 
  systemd:
    daemon_reload: yes

- name: ReStart Cart service 
  systemd:
    name: cart
    state: restarted 
    enabled: yes 

- name: Install Filebeat 
  import_role:
    name: filebeat
  vars:
    FILEBEAT_CONFIG: filebeat.yml

- name: New Relic Configuration 
  import_role:
    name: newrelic 
  vars:
    SERVICE_NAME: cart